//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetTokyo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotNetTokyo.Resources.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register your interest on Meetup.com.
        /// </summary>
        public static string CallToActionText {
            get {
                return ResourceManager.GetString("CallToActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to do a technology talk to the group or just want to show something off, in English or Japanese, email the organizer Ed Andersen: mail (at) edandersen.com..
        /// </summary>
        public static string HomepageBoxoutContent1 {
            get {
                return ResourceManager.GetString("HomepageBoxoutContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Meetup.com group for updates on our first meetup..
        /// </summary>
        public static string HomepageBoxoutContent2 {
            get {
                return ResourceManager.GetString("HomepageBoxoutContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakers and talks wanted!.
        /// </summary>
        public static string HomepageBoxoutHeader1 {
            get {
                return ResourceManager.GetString("HomepageBoxoutHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for updates.
        /// </summary>
        public static string HomepageBoxoutHeader2 {
            get {
                return ResourceManager.GetString("HomepageBoxoutHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No events are currently planned. Stay tuned for more info!.
        /// </summary>
        public static string NoUpcomingEvents {
            get {
                return ResourceManager.GetString("NoUpcomingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSVP.
        /// </summary>
        public static string RSVP {
            get {
                return ResourceManager.GetString("RSVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tokyo .NET Developers Meetup.
        /// </summary>
        public static string SiteTitle {
            get {
                return ResourceManager.GetString("SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are putting together a User Group for developers using C#, .NET, Unity 3D, Xamarin, Azure and other related technologies in the Tokyo area. Join us!.
        /// </summary>
        public static string TitleSubheading {
            get {
                return ResourceManager.GetString("TitleSubheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming events.
        /// </summary>
        public static string UpcomingEvents {
            get {
                return ResourceManager.GetString("UpcomingEvents", resourceCulture);
            }
        }
    }
}
